name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
  schedule:
    - cron: "10 4 * * 2" # Every Tuesday at 4:10 AM UTC

permissions:
  contents: read

jobs:
  tests:
    name: Pimcore ${{ matrix.pimcore-version }} / PHP ${{ matrix.php-version }} / ${{ matrix.dependencies }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: "8.1"
            pimcore-version: "^10.6"
            dependencies: "highest"

          - php-version: "8.1"
            pimcore-version: "^11.5"
            dependencies: "highest"

          - php-version: "8.2"
            pimcore-version: "^11.5"
            dependencies: "highest"

          - php-version: "8.3"
            pimcore-version: "^11.5"
            dependencies: "highest"

          - php-version: "8.3"
            pimcore-version: "^12"
            dependencies: "lowest"

          - php-version: "8.3"
            pimcore-version: "^12"
            dependencies: "highest"

          - php-version: "8.4"
            pimcore-version: "^12"
            dependencies: "highest"

    env:
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: pimcore
      MYSQL_DATABASE: pimcore
      MYSQL_SERVER_VERSION: "10.11.10-MariaDB"

    services:
      mariadb:
        image: mariadb:10.11.10
        env:
          MYSQL_ROOT_PASSWORD: pimcore
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 3306:3306

    steps:
      - name: Git Checkout
        uses: actions/checkout@v6

      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-file: development

      - name: Require specific dependencies
        run: |
          packages="pimcore/pimcore:${{ matrix.pimcore-version }}"

          case "${{ matrix.pimcore-version }}" in
            "^10.6")
              packages="$packages laminas/laminas-zendframework-bridge"
              ;;
            "^11.5")
              packages="$packages pimcore/admin-ui-classic-bundle:^1"
              ;;
            "^12")
              packages="$packages pimcore/admin-ui-classic-bundle:^2"
              ;;
          esac

          composer require --no-update $packages

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Execute tests
        env:
          PIMCORE_ENCRYPTION_SECRET: ${{ secrets.PIMCORE_ENCRYPTION_SECRET }}
          PIMCORE_INSTANCE_IDENTIFIER: ${{ secrets.PIMCORE_INSTANCE_IDENTIFIER }}
          PIMCORE_PRODUCT_KEY: ${{ secrets.PIMCORE_PRODUCT_KEY }}
        run: |
          # Ignore deprecations with "8191" = E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED
          php -d error_reporting=8191 vendor/bin/phpunit --fail-on-risky
